[build-system]
requires = ["setuptools>=64", "setuptools_scm[toml]>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "surforama"
dynamic = ["version"]
description = "a tool for using surfaces to explore volumetric data in napari"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Kyle Harrington", email = "surforama@kyleharrington.com" },
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Framework :: napari",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Image Processing",
]
requires-python = ">=3.10"
dependencies = [
    "magicgui",
    "mrcfile",
    "numpy",
    "pooch",
    "qtpy",
    "pyacvd",
    "pyvista",
    "rich",
    "scikit-image",
    "starfile",
    "trimesh",
    "typer",
]

[project.urls]
"Bug Tracker"   = "https://github.com/cellcanvas/surforama/issues"
"Documentation" = "https://github.com/cellcanvas/surforama#README.md"
"Source Code"   = "https://github.com/cellcanvas/surforama"
"User Support"  = "https://github.com/cellcanvas/surforama/issues"

[project.scripts]
surforama = "surforama._cli:app"

[project.entry-points."napari.manifest"]
surforama = "surforama:napari.yaml"

[project.optional-dependencies]
testing = [
    "napari",
    "pyqt5",
    "pytest",
    "pytest-cov",
    "pytest-qt",
    "tox",
]
docs = [
    "mkdocs<2",
    "mkdocs-material",
    "mkdocstrings[python]",
    "mkdocs-video",
]
napari = ["napari[all]"]
dev = [
    "surforama[testing,docs]",
    "pre-commit",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["*.yaml"]

[tool.setuptools_scm]
write_to = "src/surforama/_version.py"


[tool.black]
line-length = 79
target-version = ['py310', 'py311', 'py312']


[tool.ruff]
line-length = 79
select = [
    "E", "F", "W", #flake8
    "UP", # pyupgrade
    "I", # isort
    "BLE", # flake8-blind-exception
    "B", # flake8-bugbear
    "A", # flake8-builtins
    "C4", # flake8-comprehensions
    "ISC", # flake8-implicit-str-concat
    "G", # flake8-logging-format
    "PIE", # flake8-pie
    "SIM", # flake8-simplify
]
ignore = [
    "E501", # line too long. let black handle this
    "UP006", "UP007", # type annotation. As using magicgui require runtime type annotation then we disable this.
    "SIM117", # flake8-simplify - some of merged with statements are not looking great with black, reanble after drop python 3.9
]

exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".mypy_cache",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "*vendored*",
    "*_vendor*",
]

target-version = "py310"
fix = true
